apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base  # relative path to base folder

patchesStrategicMerge:
  - deployment-patch.yaml  # optional, environment-specific changes
